/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.packageadmin.categoriaestados;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static menu.packageadmin.categoriaestados.categoriaestados1.btnActualizarCatEstados;
import static menu.packageadmin.categoriaestados.categoriaestados1.btnGuardarCatEstados;
import static menu.packageadmin.categoriaestados.categoriaestados1.cbxCatEstados;
import static menu.packageadmin.categoriaestados.categoriaestados1.txtCodigoCatEstados;
import static menu.packageadmin.categoriaestados.categoriaestados1.txtNombreCatEstados;
import static menu.packageadmin.categoriaestados.categoriaestados1.txtidCatEstados;



/**
 *
 * @author CotoF
 */
public class categoriaestados extends javax.swing.JPanel {
    
    categoriaestados1 categoriaestados1 = new categoriaestados1();
    
    
    
    public static final String URL = "jdbc:mysql://localhost:3306/dreamgifts"; //Direccion, puerto y nombre de la Base de Datos
    public static final String USERNAME = "root"; //Usuario de Acceso a MySQL
    public static final String PASSWORD = ""; //Password del usuario
    
    PreparedStatement ps;
    ResultSet rs;

    public static Connection getConection() {
        Connection con = null;

        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
           // JOptionPane.showMessageDialog(null, "Conexion exitosa");

        } catch (Exception e) {
            System.out.println(e);
        }
        return con;
    }
    
                public static void limpiarCajasCatEstados(){

        txtNombreCatEstados.setText(null);
        txtCodigoCatEstados.setText(null);
        

    }
                
        public static void ActualizarAutomaticamenteCatEstados (){
        
               
        DefaultTableModel modelo = (DefaultTableModel) TablaCatEstados.getModel(); /*Tomar la tabla el modelo que ya estamos agregando*/
   /*se necesita para ocultar la id de la tabla, este dato se necesita para la modificacion*/
        modelo.setRowCount(0);/*Para que siempre que se ejecute reinicie las filas existentes*/ 
        
        PreparedStatement ps; /*Declarar unas variables para hacer las transacciones*/
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        
        int [] ancho = {30,80,60,0}; /*Arreglo con el ancho de las columnas*/
        for  (int i = 0; i< TablaCatEstados.getColumnCount(); i++){ /*consulta a la tabla el numero de columna que tiene*/
        TablaCatEstados.getColumnModel().getColumn(3).setMaxWidth(0);
        TablaCatEstados.getColumnModel().getColumn(3).setMinWidth(0);
        TablaCatEstados.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        TablaCatEstados.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);
        TablaCatEstados.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]); 
        btnEditarCatEstados.setEnabled(false);
        
             
        }   
        
        Connection con = null;
        try { 
            con = getConection();
            ps= con.prepareStatement ("SELECT tipo_evento,codigo,estado,id_tipo_evento FROM tipo_eventos");
       
            rs= ps.executeQuery();
            rsmd = rs.getMetaData ();
            columnas = rsmd.getColumnCount(); /*Cuantas Columnas trae esta consulta*/
            
            
            while(rs.next()){ /*Extraer todo los datos de la consulta*/
               Object[] filas = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);

            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }


    /**
     * Creates new form categoriaestados
     */
    public categoriaestados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCatEstados = new javax.swing.JTable();
        btnEditarCatEstados = new javax.swing.JButton();
        btnNuevoCatEstados = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        TablaCatEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Categoria estado", "Codigo", "Estado", "Id_CatEstados"
            }
        ));
        TablaCatEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCatEstadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCatEstados);

        btnEditarCatEstados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarCatEstados.setText("Editar");
        btnEditarCatEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarCatEstadosMouseClicked(evt);
            }
        });
        btnEditarCatEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatEstadosActionPerformed(evt);
            }
        });

        btnNuevoCatEstados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevoCatEstados.setText("Nueva categoria estados");
        btnNuevoCatEstados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoCatEstadosMouseClicked(evt);
            }
        });
        btnNuevoCatEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoCatEstadosActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(102, 44));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Categoria estados");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(btnEditarCatEstados)
                .addContainerGap(701, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnNuevoCatEstados)
                            .addGap(558, 558, 558)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnEditarCatEstados)
                .addContainerGap(411, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevoCatEstados)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TablaCatEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCatEstadosMouseClicked

        int fila = TablaCatEstados.getSelectedRow();

        txtNombreCatEstados.setText(TablaCatEstados.getValueAt(fila, 0).toString());
        txtCodigoCatEstados.setText(TablaCatEstados.getValueAt(fila, 1).toString());
        cbxCatEstados.setSelectedItem(TablaCatEstados.getValueAt(fila, 2).toString());
        txtidCatEstados.setText(TablaCatEstados.getModel().getValueAt(TablaCatEstados.getSelectedRow(),3).toString());
        btnEditarCatEstados.setEnabled(true);
    }//GEN-LAST:event_TablaCatEstadosMouseClicked

    private void btnEditarCatEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarCatEstadosMouseClicked
        categoriaestados1.setVisible(true);
        btnActualizarCatEstados.setEnabled(true);
        btnGuardarCatEstados.setEnabled(false);
    }//GEN-LAST:event_btnEditarCatEstadosMouseClicked

    private void btnNuevoCatEstadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoCatEstadosMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoCatEstadosMouseClicked

    private void btnNuevoCatEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoCatEstadosActionPerformed
        limpiarCajasCatEstados();
        categoriaestados1.setVisible(true);
        btnGuardarCatEstados.setEnabled(true);
        btnActualizarCatEstados.setEnabled(false);
    }//GEN-LAST:event_btnNuevoCatEstadosActionPerformed

    private void btnEditarCatEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCatEstadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaCatEstados;
    public static javax.swing.JButton btnEditarCatEstados;
    public static javax.swing.JButton btnNuevoCatEstados;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
