/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu.packageadmin.rrss;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static menu.packageadmin.rrss.rrss1.btnActualizarRRSS;
import static menu.packageadmin.rrss.rrss1.btnGuardarRRSS;
import static menu.packageadmin.rrss.rrss1.cbxEstadoRRSS;
import static menu.packageadmin.rrss.rrss1.txtCodigoRRSS;
import static menu.packageadmin.rrss.rrss1.txtNombreRRSS;

/**
 *
 * @author CotoF
 */
public class rrss extends javax.swing.JPanel {
        rrss1 rrss1 =new rrss1();

    public static final String URL = "jdbc:mysql://localhost:3306/dreamgifts"; //Direccion, puerto y nombre de la Base de Datos
    public static final String USERNAME = "root"; //Usuario de Acceso a MySQL
    public static final String PASSWORD = ""; //Password del usuario
    
    PreparedStatement ps;
    ResultSet rs;

    public static Connection getConection() {
        Connection con = null;

        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
           // JOptionPane.showMessageDialog(null, "Conexion exitosa");

        } catch (Exception e) {
            System.out.println(e);
        }
        return con;
    }

        public static void limpiarCajasRRSS(){

        txtNombreRRSS.setText(null);
        txtCodigoRRSS.setText(null);
        

    }

        public static void ActualizarAutomaticamenteRRSS (){
        
               
        DefaultTableModel modelo = (DefaultTableModel) TablaRRSS.getModel(); /*Tomar la tabla el modelo que ya estamos agregando*/
   /*se necesita para ocultar la id de la tabla, este dato se necesita para la modificacion*/
        modelo.setRowCount(0);/*Para que siempre que se ejecute reinicie las filas existentes*/ 
        
        PreparedStatement ps; /*Declarar unas variables para hacer las transacciones*/
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        
        int [] ancho = {30,80,60,0}; /*Arreglo con el ancho de las columnas*/
        for  (int i = 0; i< TablaRRSS.getColumnCount(); i++){ /*consulta a la tabla el numero de columna que tiene*/
        TablaRRSS.getColumnModel().getColumn(3).setMaxWidth(0);
        TablaRRSS.getColumnModel().getColumn(3).setMinWidth(0);
        TablaRRSS.getTableHeader().getColumnModel().getColumn(3).setMaxWidth(0);
        TablaRRSS.getTableHeader().getColumnModel().getColumn(3).setMinWidth(0);
        TablaRRSS.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]); 
        btnEditarRRSS.setEnabled(false);
        
             
        }   
        
        Connection con = null;
        try { 
            con = getConection();
            ps= con.prepareStatement ("SELECT nombre,codigoRRSS,estado,idRedes FROM redes");
       
            rs= ps.executeQuery();
            rsmd = rs.getMetaData ();
            columnas = rsmd.getColumnCount(); /*Cuantas Columnas trae esta consulta*/
            
            
            while(rs.next()){ /*Extraer todo los datos de la consulta*/
               Object[] filas = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);

            }
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    /**
     * Creates new form rrss
     */
    public rrss() {
        initComponents();
        ActualizarAutomaticamenteRRSS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarRRSS = new javax.swing.JButton();
        btnNuevoRRSS = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRRSS = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtidRRSS = new javax.swing.JTextField();

        btnEditarRRSS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarRRSS.setText("Editar");
        btnEditarRRSS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarRRSSMouseClicked(evt);
            }
        });

        btnNuevoRRSS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevoRRSS.setText("Nueva red social");
        btnNuevoRRSS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoRRSSMouseClicked(evt);
            }
        });
        btnNuevoRRSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRRSSActionPerformed(evt);
            }
        });

        TablaRRSS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre ", "Codigo", "Estado", "Id_RRSS"
            }
        ));
        TablaRRSS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaRRSSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaRRSS);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Buscar");

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(102, 44));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Redes sociales");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtidRRSS.setText("a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 974, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevoRRSS)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarRRSS)
                        .addGap(142, 142, 142)
                        .addComponent(txtidRRSS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 994, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarRRSS)
                        .addComponent(btnNuevoRRSS)
                        .addComponent(txtidRRSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoRRSSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoRRSSMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoRRSSMouseClicked

    private void btnNuevoRRSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRRSSActionPerformed
        limpiarCajasRRSS();
        rrss1.setVisible(true);
        btnGuardarRRSS.setEnabled(true);
        btnActualizarRRSS.setEnabled(false);
    }//GEN-LAST:event_btnNuevoRRSSActionPerformed

    private void TablaRRSSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaRRSSMouseClicked
                     
        int fila = TablaRRSS.getSelectedRow();
                        
        txtNombreRRSS.setText(TablaRRSS.getValueAt(fila, 0).toString());    
        txtCodigoRRSS.setText(TablaRRSS.getValueAt(fila, 1).toString()); 
        cbxEstadoRRSS.setSelectedItem(TablaRRSS.getValueAt(fila, 2).toString());
        txtidRRSS.setText(TablaRRSS.getModel().getValueAt(TablaRRSS.getSelectedRow(),3).toString());
        btnEditarRRSS.setEnabled(true);
    }//GEN-LAST:event_TablaRRSSMouseClicked

    private void btnEditarRRSSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarRRSSMouseClicked
        rrss1.setVisible(true);
        btnActualizarRRSS.setEnabled(true);
        btnGuardarRRSS.setEnabled(false);
    }//GEN-LAST:event_btnEditarRRSSMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaRRSS;
    public static javax.swing.JButton btnEditarRRSS;
    public static javax.swing.JButton btnNuevoRRSS;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField txtidRRSS;
    // End of variables declaration//GEN-END:variables
}
